apiVersion: v1
kind: Service
metadata:
  name: webhook-adapter
  labels:
    run: webhook-adapter
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 8080
    protocol: TCP
  externalIPs: []
  type: NodePort

  selector:
    app: webhook-adapter
